#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0+
#
# Build U-Boot for the Raspberry Pi 5 in a container.
#
# Usage:
#   docker/build.sh [--mrproper] [defconfig] [make-args...]
#
#   docker/build.sh                             # rpi5_circle_net_defconfig
#   docker/build.sh rpi5_circle_defconfig       # the SD-card-only variant
#   docker/build.sh rpi5_circle_net_defconfig V=1
#   docker/build.sh --mrproper                  # clear a stale in-tree build first
#
# Output goes to build-docker/ so that it never collides with a native build
# in the same worktree.  Override with KBUILD_OUTPUT=<dir>.

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

mrproper=0
if [ "${1:-}" = "--mrproper" ]; then
	mrproper=1
	shift
fi

defconfig=${1:-rpi5_circle_net_defconfig}
shift || true

if [ ! -f "$repo/configs/$defconfig" ]; then
	echo "build.sh: no such defconfig: configs/$defconfig" >&2
	echo "available rpi5 configs:" >&2
	ls "$repo/configs" | grep '^rpi5' | sed 's/^/  /' >&2
	exit 1
fi

out=${KBUILD_OUTPUT:-build-docker}

ensure_image

# kbuild refuses an out-of-tree build while the source tree still holds an
# in-tree one (Makefile:634, the "source tree is not clean" check).  A tree
# that has been built natively with a bare "make" will trip this, and the two
# build styles cannot coexist -- clearing it once is the only way through.
if [ -f "$repo/.config" ] ||
   [ -d "$repo/include/config" ] ||
   [ -d "$repo/arch/arm/include/generated" ]; then
	if [ "$mrproper" = 1 ]; then
		echo ">> make mrproper (clearing in-tree build)" >&2
		KBUILD_OUTPUT= uboot_run make mrproper
	else
		cat >&2 <<-MSG

		build.sh: the source tree holds a native in-tree build.

		kbuild will not build out of tree while $repo
		contains .config, include/config/ or arch/arm/include/generated/,
		and the container builds out of tree so that it does not link
		against objects left by a different compiler.

		Clearing it deletes the in-tree build products -- u-boot.bin,
		.config, System.map and the object files -- all of which are
		regenerated by the next build.  Then:

		    docker/build.sh --mrproper $defconfig

		or run "make mrproper" on the host yourself first.

		MSG
		exit 1
	fi
fi

echo ">> $defconfig -> $out/" >&2
uboot_run make "$defconfig"
uboot_run make -j"$(nproc)" "$@"

echo >&2
ls -l "$repo/$out/u-boot.bin" >&2
