// SPDX-License-Identifier: GPL-2.0+
/*
 * The single page served by U-Boot's HTTP server (net/httpd.c).
 *
 * Copyright (C) 2026 U-Boot contributors
 *
 * It is kept in its own file so that the markup does not bury the protocol
 * code, and it is deliberately self-contained: no favicon, no fonts and no
 * scripts are fetched from anywhere.  U-Boot's legacy TCP has room for a
 * single connection at a time, so every extra request the browser makes is
 * a request that has to wait for a SYN retry - one page, one connection.
 *
 * For the same reason the script never has two requests in flight.
 */

#include <net/httpd.h>

const char httpd_page[] =
"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<link rel='icon' href='data:,'><title>U-Boot storage loader</title><style>"
":root{color-scheme:dark;--bg:#12161c;--card:#1b212a;--line:#2c3543;"
"--fg:#e6edf3;--dim:#93a1b1;--acc:#4c9aff;--ok:#3fb950;--err:#f85149}"
"*{box-sizing:border-box}"
"body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,"
"-apple-system,Segoe UI,Roboto,sans-serif}"
"header{display:flex;flex-wrap:wrap;gap:8px;align-items:baseline;"
"justify-content:space-between;padding:18px 20px;border-bottom:1px solid var(--line)}"
"h1{margin:0;font-size:19px;letter-spacing:.2px}"
"h2{margin:0 0 12px;font-size:13px;text-transform:uppercase;"
"letter-spacing:.08em;color:var(--dim)}"
"main{max-width:760px;margin:0 auto;padding:20px}"
".card{background:var(--card);border:1px solid var(--line);border-radius:10px;"
"padding:16px 18px;margin-bottom:16px}"
"label{display:block;margin-bottom:6px;color:var(--dim);font-size:13px}"
"select,input[type=text]{width:100%;padding:9px 10px;background:#10141a;"
"color:var(--fg);border:1px solid var(--line);border-radius:6px;font:inherit}"
"button{padding:9px 16px;border:0;border-radius:6px;background:var(--acc);"
"color:#04101f;font:600 14px/1 inherit;cursor:pointer}"
"button:disabled{opacity:.45;cursor:default}"
"button.ghost{background:transparent;color:var(--fg);border:1px solid var(--line)}"
".row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}"
".row>*{flex:0 0 auto}.grow{flex:1 1 180px}"
"#drop{display:block;border:1.5px dashed var(--line);border-radius:8px;"
"padding:22px;text-align:center;color:var(--dim);cursor:pointer;margin:0 0 12px}"
"#drop.over{border-color:var(--acc);background:#182233;color:var(--fg)}"
"#file{display:none}"
"#bar{height:8px;background:#10141a;border-radius:4px;overflow:hidden;"
"margin:14px 0 8px;display:none}"
"#fill{height:100%;width:0;background:var(--acc);transition:width .15s}"
"#msg{min-height:20px;font-size:14px}"
".ok{color:var(--ok)}.err{color:var(--err)}.dim{color:var(--dim)}"
"table{width:100%;border-collapse:collapse;font-size:14px}"
"td{padding:4px 6px;border-bottom:1px solid var(--line)}"
"td.sz{text-align:right;color:var(--dim);white-space:nowrap}"
"footer{display:flex;justify-content:space-between;align-items:center;"
"gap:12px;flex-wrap:wrap;color:var(--dim);font-size:13px}"
"</style></head><body>"
"<header><h1>U-Boot storage loader</h1><span class='dim' id='host'></span></header>"
"<main>"
"<section class='card'><h2>1 &middot; Target</h2>"
"<div class='row'><div class='grow'><select id='target'></select></div>"
"<button class='ghost' id='rescan'>Rescan</button></div></section>"
"<section class='card'><h2>2 &middot; File</h2>"
"<label id='drop' for='file'><span id='dropmsg'><b>Choose a file</b>"
" or drop it here</span></label><input id='file' type='file'>"
"<label for='name'>Save as</label><input id='name' type='text' "
"placeholder='kernel_2712.img' autocomplete='off'>"
"<div id='bar'><div id='fill'></div></div>"
"<div class='row' style='margin-top:12px'>"
"<button id='send' disabled>Write to storage</button>"
"<span id='msg' class='dim'></span></div></section>"
"<section class='card'><h2>Files on target</h2>"
"<div class='row' style='margin-bottom:10px'>"
"<button class='ghost' id='ls'>Refresh listing</button>"
"<span class='dim' id='lsmsg'></span></div>"
"<table id='files'></table></section>"
"<footer><span>Serving from U-Boot &middot; the board is waiting</span>"
"<button class='ghost' id='boot'>Continue boot</button></footer>"
"</main><script>\n"
"var $=function(s){return document.getElementById(s)};\n"
"var picked=null,busy=false;\n"
"function human(n){var u=['B','KiB','MiB','GiB','TiB'],i=0;n=Number(n);\n"
" while(n>=1024&&i<u.length-1){n/=1024;i++}\n"
" return (i?n.toFixed(n<10?2:1):n)+' '+u[i]}\n"
"function say(t,c){var m=$('msg');m.textContent=t;m.className=c||'dim'}\n"
"function lock(b){busy=b;$('send').disabled=b||!picked;$('ls').disabled=b;\n"
" $('rescan').disabled=b;$('boot').disabled=b}\n"
"function get(u){return fetch(u,{cache:'no-store'}).then(function(r){\n"
" return r.json()})}\n"
"function target(){var v=$('target').value;if(!v)return null;\n"
" var p=v.split(' ');return {iface:p[0],part:p[1]}}\n"
"function loadTargets(){say('');\n"
" return get('/api/targets').then(function(d){\n"
"  $('host').textContent=d.ip?('http://'+d.ip+'/'):'';\n"
"  var s=$('target');s.innerHTML='';\n"
"  (d.targets||[]).forEach(function(t){var o=document.createElement('option');\n"
"   o.value=t.iface+' '+t.id;\n"
"   o.textContent=t.iface+' '+t.id+'  \\u2014  '+(t.fs||'unknown fs')+', '+\n"
"    human(t.bytes)+(t.name?('  ['+t.name+']'):'');\n"
"   s.appendChild(o)});\n"
"  if(!s.options.length){var o=document.createElement('option');\n"
"   o.textContent='no SD/eMMC partition found';s.appendChild(o);\n"
"   say('No writable partition was found on mmc.','err')}\n"
" }).catch(function(e){say('Cannot read targets: '+e,'err')})}\n"
"function listFiles(){var t=target();if(!t||busy)return;\n"
" $('lsmsg').textContent='reading...';lock(true);\n"
" return get('/api/list?iface='+encodeURIComponent(t.iface)+'&part='+\n"
"  encodeURIComponent(t.part)+'&dir=/').then(function(d){\n"
"  var tb=$('files');tb.innerHTML='';\n"
"  if(!d.ok){$('lsmsg').textContent=d.error||'cannot list';lock(false);return}\n"
"  d.entries.forEach(function(e){var r=tb.insertRow();\n"
"   r.insertCell().textContent=e.dir?(e.name+'/'):e.name;\n"
"   var c=r.insertCell();c.className='sz';\n"
"   c.textContent=e.dir?'':human(e.size)});\n"
"  $('lsmsg').textContent=d.entries.length+' entries'+(d.truncated?' (truncated)':'');\n"
"  lock(false)}).catch(function(e){$('lsmsg').textContent=''+e;lock(false)})}\n"
"function pick(f){picked=f;\n"
" $('dropmsg').innerHTML='<b>'+f.name+'</b><br>'+human(f.size);\n"
" if(!$('name').value)$('name').value=f.name.replace(/^.*[\\\\/]/,'');\n"
" $('send').disabled=busy;say('')}\n"
"$('file').addEventListener('change',function(e){if(e.target.files[0])\n"
" pick(e.target.files[0])});\n"
"['dragenter','dragover'].forEach(function(n){$('drop').addEventListener(n,\n"
" function(e){e.preventDefault();$('drop').classList.add('over')})});\n"
"['dragleave','drop'].forEach(function(n){$('drop').addEventListener(n,\n"
" function(e){e.preventDefault();$('drop').classList.remove('over')})});\n"
"$('drop').addEventListener('drop',function(e){\n"
" if(e.dataTransfer.files[0])pick(e.dataTransfer.files[0])});\n"
"$('rescan').addEventListener('click',function(){if(!busy)loadTargets()});\n"
"$('ls').addEventListener('click',listFiles);\n"
"$('send').addEventListener('click',function(){\n"
" var t=target(),name=$('name').value.trim();\n"
" if(!picked||!t){say('Pick a file and a target first.','err');return}\n"
" if(!name){say('A destination file name is needed.','err');return}\n"
" var fd=new FormData();\n"
" fd.append('iface',t.iface);fd.append('part',t.part);fd.append('name',name);\n"
" fd.append('file',picked,name);\n"
" var x=new XMLHttpRequest();\n"
" x.open('POST','/api/upload');\n"
" $('bar').style.display='block';$('fill').style.width='0';\n"
" lock(true);say('Uploading '+human(picked.size)+'...');\n"
" x.upload.onprogress=function(e){if(!e.lengthComputable)return;\n"
"  var p=Math.round(e.loaded*100/e.total);$('fill').style.width=p+'%';\n"
"  say(p<100?('Uploading '+p+'%'):'Writing to storage...')};\n"
" x.onload=function(){lock(false);var d={};\n"
"  try{d=JSON.parse(x.responseText)}catch(err){}\n"
"  if(x.status===200&&d.ok){$('fill').style.width='100%';\n"
"   say('Wrote '+human(d.bytes)+' to '+d.iface+' '+d.part+' as '+d.name,'ok');\n"
"   listFiles()}\n"
"  else{say('Failed: '+(d.error||('HTTP '+x.status)),'err')}};\n"
" x.onerror=function(){lock(false);say('Upload failed: connection lost','err')};\n"
" x.send(fd)});\n"
"$('boot').addEventListener('click',function(){\n"
" if(!confirm('Stop the web UI and continue booting?'))return;\n"
" lock(true);say('Handing the board back to the boot command...');\n"
" fetch('/api/boot',{method:'POST'}).then(function(){\n"
"  document.body.innerHTML='<main><section class=\\'card\\'>'+\n"
"   '<h2>Booting</h2>The board has resumed its boot command. '+\n"
"   'This page is no longer served.</section></main>'})\n"
" .catch(function(){document.body.innerHTML='<main><section class=\\'card\\'>'+\n"
"   '<h2>Booting</h2>The board has resumed its boot command.'+\n"
"   '</section></main>'})});\n"
"loadTargets().then(listFiles);\n"
"</script></body></html>";

const unsigned int httpd_page_len = sizeof(httpd_page) - 1;
